export const approvedBrands = [
  "1017 ALYX 9SM",
  "14th Addiction",
  "20471120",
  "A&G",
  "Acne Studios",
  "Acronym",
  "Adidas",
  "Alexander McQueen",
  "Ambush",
  "Ann Demeulemeester",
  "Anonymous Club",
  "APC",
  "Arc'Teryx",
  "Armani",
  "ASICS",
  "Balenciaga",
  "Balmain",
  "Beauty : Beast",
  "Been Trill",
  "Blackmeans",
  "Bode",
  "Boris Bidjan Saberi",
  "Bottega Veneta",
  "Brunello Cucinelli",
  "Burberry",
  "C.P. Company",
  "Calvin Klein",
  "Canada Goose",
  "Carhartt",
  "Carol Christian Poell",
  "Casablanca",
  "Celine",
  "Chanel",
  "Chito",
  "Chrome Hearts",
  "Christian Louboutin",
  "Comme Des Garcons",
  "Common Projects",
  "Denim Tears",
  "Dirk Bikkembergs",
  "Dior",
  "Dolce & Gabbana",
  "Dr. Martens",
  "Dries Van Noten",
  "DSquared2",
  "Endless",
  "Engineered Garments",
  "Enfants Riches Deprimes",
  "Eric Emmanuel",
  "Essentials",
  "Evisu",
  "Fear of God",
  "Gallery Dept",
  "Givenchy",
  "Goyard",
  "Greg Lauren",
  "Guidi",
  "Haider Ackermann",
  "Helmut Lang",
  "Hermes",
  "Heron Preston",
  "Hidden.NY",
  "Hood By Air",
  "Hysteric Glamour",
  "If Six Was Nine",
  "Isaac Selam",
  "Isabel Marant",
  "Issey Miyake",
  "Jacques Marie Mage",
  "Jean Paul Gaultier",
  "JJJound",
  "Jil Sander",
  "John Elliott",
  "Julius",
  "Junya Watanabe",
  "Kapital",
  "Kaws",
  "Kenzo",
  "Kiko Kostadinov",
  "Kmrii",
  "Ksubi",
  "L.G.B.",
  "Lemaire",
  "Levi's",
  "Loewe",
  "Loro Piana",
  "Maison Margiela",
  "Maison Mihara Yasuhiro",
  "Marithe Francois Girbaud",
  "Marni",
  "Martine Rose",
  "Mastermind",
  "Matty Boy",
  "Missoni",
  "Miu Miu",
  "Moncler",
  "Mowalola",
  "Moose Knuckle",
  "Needles",
  "Neil Barrett",
  "New Balance",
  "Norse Projects",
  "Number (N)ine",
  "Off-White",
  "Officine Generale",
  "Omega",
  "Palace",
  "Palm Angels",
  "PDF",
  "Prada",
  "Purple Brand",
  "Raf Simons",
  "Rag & Bone",
  "Ralph Lauren",
  "Ralph Lauren Purple Label",
  "Raspberry Hills",
  "ReadyMade",
  "Reebok",
  "Rhude",
  "Rick Owens",
  "Rick Owens DRKSHDW",
  "Ripvanwinkle",
  "Rivington roi Rebis",
  "Robert Cavalli",
  "Sacai",
  "Saint Laurent",
  "Saint Michael",
  "Salvatore Ferragamo",
  "Sasquatchfabrix",
  "Satoshi Nakamoto",
  "Seditionaries",
  "Sicko",
  "South2 West8",
  "Sterling Ruby",
  "Stone Island",
  "Stray Rats",
  "Stussy",
  "Supreme",
  "TAKAHIROMIYASHITA The SoloIst.",
  "Takashi Murakami",
  "The Elder Statesman",
  "The Row",
  "Thom Browne",
  "Tiffany & Co.",
  "Tom Ford",
  "Tornado Mart",
  "Undercover",
  "Valentino",
  "Vans",
  "Versace",
  "Vetements",
  "Vivienne Westwood",
  "Vlone",
  "Visvim",
  "WTAPS",
  "Y-3",
  "Yeezy",
  "Yohji Yamamoto",
  "YZY",
  "Ziggy Chen",
  "Coperni",
  "Bape",
  "Hellstar",
  "Better With Age",
  "Gucci",
  "Louis Vuitton",
  "Our Legacy",
  "Paly",
  "Sinclair",
  "Amiri",
  "ROA",
  "Vale",
  "Knickerbocker",
  "Kith",
  "Junya Wanatabe",
  "Dolce Gabbana",
  "Ottolinger",
  "Nike",
  "Jacquemus",
  "Eric Emanuel",
  "Diesel",
  "Godspeed",
  "Lanvin",
  "Telfar",
  "Chloe",
  "Marine Serre",
  "PPFM",
  "RRL",
  "Brioni",
  "Zegna",
  "Paul Stuart",
  "Longhi",
  "Human Made",
  "Vertabrae",
  "Jimmy Choo",
  "Erl",
  "Proenza Schouler",
  "Roland Mouret",
  "Yigal Azrouel",
  "5351 Pour Les Hommes",
  "Mihara Yashiro",
  "424",
];
